# Generated by Django 4.2.3 on 2023-08-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=32, unique=True, verbose_name='상품 이름')),
                ('item_price', models.IntegerField(verbose_name='상품 가격')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=32, unique=True, verbose_name='토핑 이름')),
                ('topping_price', models.IntegerField(verbose_name='토핑 가격')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.item', verbose_name='상품 이름')),
            ],
        ),
    ]
