# Generated by Django 4.2.3 on 2023-08-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': '토핑', 'verbose_name_plural': '토핑'},
        ),
    ]
